INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES(1, 'DENNYS', 'FREDERICCI');

INSERT INTO CONTACTINFO(ID, PERSON_ID, PHONENUMBER, EMAIL, ADDRESS, CITY, ZIPCODE, COUNTRY) VALUES(1, 1, '0493256644', 'YOUR@EMAIL.COM', 'CANTERSTEEN 12', 'BRUSSELS', '1000', 'BELGIUM');
